export const photos = {
  hero: "/images/Hero Section.jpg",

  front: "/images/48-web-or-mls-18334 Hiawatha St by Pierre Galant-2-3.jpg",
  night: "/images/95c401b8f69bf40a7c687905a1c216db.JPG",

  living: "/images/10-web-or-mls-18334 Hiawatha St by Pierre Galant-10.jpg",
  livingAlt: "/images/13-web-or-mls-18334 Hiawatha St by Pierre Galant-2-2.jpg",
  livingDetail: "/images/14-web-or-mls-18334 Hiawatha St by Pierre Galant-1-2.jpg",
  livingWide: "/images/17-web-or-mls-18334 Hiawatha St by Pierre Galant-17.jpg",
  livingDining: "/images/19-web-or-mls-18334 Hiawatha St by Pierre Galant-19.jpg",

  kitchen: "/images/21-web-or-mls-18334 Hiawatha St by Pierre Galant-21.jpg",
  kitchenDining: "/images/20-web-or-mls-18334 Hiawatha St by Pierre Galant-20.jpg",
  hall: "/images/6-web-or-mls-18334 Hiawatha St by Pierre Galant-6.jpg",

  bedroom: "/images/47-web-or-mls-18334 Hiawatha St by Pierre Galant-1-4.jpg",
  bedroomAlt: "/images/49-web-or-mls-18334 Hiawatha St by Pierre Galant-3-2.jpg",
  bedroomWide: "/images/50-web-or-mls-18334 Hiawatha St by Pierre Galant-4-2.jpg",
  bathroom: "/images/51-web-or-mls-18334 Hiawatha St by Pierre Galant-6-2.jpg",

  entrance: "/images/52-web-or-mls-18334 Hiawatha St by Pierre Galant-1-5.jpg",
  exterior: "/images/46-web-or-mls-18334 Hiawatha St by Pierre Galant-1-3.jpg",
  exteriorAlt: "/images/34-web-or-mls-18334 Hiawatha St by Pierre Galant-34.jpg",
  exteriorDetail: "/images/7-web-or-mls-18334 Hiawatha St by Pierre Galant-7.jpg",
  exteriorGarden: "/images/5-web-or-mls-18334 Hiawatha St by Pierre Galant-5.jpg",

  pool: "/images/32-web-or-mls-18334 Hiawatha St by Pierre Galant-32.jpg",
  poolWide: "/images/34-web-or-mls-18334 Hiawatha St by Pierre Galant-34.jpg",
  poolPatio: "/images/24-web-or-mls-18334 Hiawatha St by Pierre Galant-24.jpg",
  poolPatioAlt: "/images/25-web-or-mls-18334 Hiawatha St by Pierre Galant-25.jpg",
  poolAerial: "/images/37-web-or-mls-18334 Hiawatha St by Pierre Galant-37.jpg",
  aerial: "/images/45-web-or-mls-18334 Hiawatha St by Pierre Galant-45.jpg",

  courtyard: "/images/courtyard.webp",
  garden: "/images/garden.jpg",
  gardenHome: "/images/garden-home.jpg",
  architects: "/images/architects.webp",

  studioMain: "/images/studio-main.webp",
  studioRoom: "/images/studio-room.webp",
  studioBooth: "/images/studio-booth.jpg",

  frontLegacy: "/images/front.webp",
  heroLegacy: "/images/hero.jpg",
  bedroomLegacy: "/images/bedroom.webp",
  kitchenLegacy: "/images/kitchen.webp",
  livingLegacy: "/images/living.webp",
  poolLegacy: "/images/pool.webp",
  poolWideLegacy: "/images/pool-wide.jpg",
  nightLegacy: "/images/night.webp",

  gallery: [
    ["/images/Hero Section.jpg", "Sunlit living room opening to the garden", "Living / 01"],
    ["/images/10-web-or-mls-18334 Hiawatha St by Pierre Galant-10.jpg", "Living room with floor-to-ceiling glass and exposed beams", "Living / 02"],
    ["/images/13-web-or-mls-18334 Hiawatha St by Pierre Galant-2-2.jpg", "Open living area with original architectural character", "Living / 03"],
    ["/images/14-web-or-mls-18334 Hiawatha St by Pierre Galant-1-2.jpg", "Living room with fireplace and wood detailing", "Living / 04"],
    ["/images/17-web-or-mls-18334 Hiawatha St by Pierre Galant-17.jpg", "Living room and garden connection", "Living / 05"],
    ["/images/19-web-or-mls-18334 Hiawatha St by Pierre Galant-19.jpg", "Dining area connected to the living space", "Dining / 01"],
    ["/images/20-web-or-mls-18334 Hiawatha St by Pierre Galant-20.jpg", "Kitchen and dining area", "Kitchen / 01"],
    ["/images/21-web-or-mls-18334 Hiawatha St by Pierre Galant-21.jpg", "Bright white kitchen", "Kitchen / 02"],
    ["/images/219e5289af25a4616234bb4249f65056.JPG", "Interior view emphasizing the glass walls and beams", "Interior / 01"],
    ["/images/5-web-or-mls-18334 Hiawatha St by Pierre Galant-5.jpg", "Interior view toward the garden", "Interior / 02"],
    ["/images/6-web-or-mls-18334 Hiawatha St by Pierre Galant-6.jpg", "Interior workspace beside the garden", "Interior / 03"],
    ["/images/7-web-or-mls-18334 Hiawatha St by Pierre Galant-7.jpg", "Sunlit interior and garden connection", "Interior / 04"],
    ["/images/95c401b8f69bf40a7c687905a1c216db.JPG", "Living room with original architectural character", "Interior / 05"],
    ["/images/24-web-or-mls-18334 Hiawatha St by Pierre Galant-24.jpg", "Covered outdoor living area beside the pool", "Outdoor / 01"],
    ["/images/25-web-or-mls-18334 Hiawatha St by Pierre Galant-25.jpg", "Outdoor dining area overlooking the pool", "Outdoor / 02"],
    ["/images/32-web-or-mls-18334 Hiawatha St by Pierre Galant-32.jpg", "Private swimming pool surrounded by palms", "Pool / 01"],
    ["/images/34-web-or-mls-18334 Hiawatha St by Pierre Galant-34.jpg", "Mid-century home and private pool", "Pool / 02"],
    ["/images/37-web-or-mls-18334 Hiawatha St by Pierre Galant-37.jpg", "Aerial view of the swimming pool and property", "Pool / 03"],
    ["/images/45-web-or-mls-18334 Hiawatha St by Pierre Galant-45.jpg", "Aerial view of 18334 Hiawatha and the neighborhood", "Aerial / 01"],
    ["/images/46-web-or-mls-18334 Hiawatha St by Pierre Galant-1-3.jpg", "Street-facing exterior and front garden", "Exterior / 01"],
    ["/images/48-web-or-mls-18334 Hiawatha St by Pierre Galant-2-3.jpg", "Front exterior with mature landscaping", "Exterior / 02"],
    ["/images/52-web-or-mls-18334 Hiawatha St by Pierre Galant-1-5.jpg", "Original architectural entry", "Entry / 01"],
    ["/images/47-web-or-mls-18334 Hiawatha St by Pierre Galant-1-4.jpg", "Bright bedroom with large window", "Bedroom / 01"],
    ["/images/49-web-or-mls-18334 Hiawatha St by Pierre Galant-3-2.jpg", "Bedroom with natural light", "Bedroom / 02"],
    ["/images/50-web-or-mls-18334 Hiawatha St by Pierre Galant-4-2.jpg", "Bedroom with garden-facing window", "Bedroom / 03"],
    ["/images/51-web-or-mls-18334 Hiawatha St by Pierre Galant-6-2.jpg", "Modern bathroom with tiled walls", "Bathroom / 01"],
  ],
} as const;

export const propertyFacts = [
  ["Architects", "Dan Palmer & William Krisel, AIA"],
  ["Development", "Living-Conditioned Homes"],
  ["Year built", "1958"],
  ["Style", "Mid-Century Modern · post-and-beam"],
  ["Bedrooms", "3"],
  ["Bathrooms", "2"],
  ["Living area", "Approx. 1,890 sq. ft."],
  ["Lot size", "Approx. 11,100 sq. ft."],
] as const;
