import { InquireBand, Photo, SectionLabel, SiteLayout, TextLink } from "@/components/site-layout";
import { photos } from "@/lib/property";
import type { Metadata } from "next";
export const metadata: Metadata = { title:"The Architecture | 18334 Hiawatha", description:"Discover the 1958 Palmer & Krisel architecture, butterfly roofline, and Living-Conditioned Homes history at 18334 Hiawatha." };


function Architecture() {
  return <SiteLayout>
    <section className="site-container grid gap-10 pt-36 pb-18 sm:pt-44 md:grid-cols-12 md:items-center"><div className="md:col-span-5"><SectionLabel>01 / The Architecture</SectionLabel><h1 className="mt-6 max-w-[12ch] font-display text-5xl leading-[1.07] sm:text-6xl">Built for living, not just looking.</h1><p className="mt-7 max-w-md leading-relaxed text-muted-foreground">In 1958, Dan Palmer and William Krisel brought a new kind of modernism to the San Fernando Valley. This home remains part of that story.</p></div><Photo src={photos.front} alt="Original butterfly roofline and street-facing entrance of 18334 Hiawatha" eager className="aspect-[6/5] md:col-span-7" /></section>
    <section className="border-y border-border bg-secondary/60 py-20"><div className="site-container grid gap-12 md:grid-cols-12"><div className="md:col-span-4"><SectionLabel>Living-Conditioned Homes</SectionLabel><h2 className="mt-5 font-display text-4xl leading-tight">A modern idea with a human heart.</h2></div><div className="space-y-5 leading-relaxed text-muted-foreground md:col-span-7 md:col-start-6"><p>In the late 1950s, Palmer and Krisel set out to bring modernism out of the museum and into daily life. They called the result Living-Conditioned Homes: houses meant not simply to be admired, but inhabited.</p><p>Built from five basic plans, the neighborhood was varied in orientation, setback, and finish. The effect is harmonious without repetition. This residence still wears the tract's defining butterfly roofline.</p><p>Walls of glass soften the boundary between home and garden; exposed beams and clerestory light give everyday rooms a quiet drama.</p></div></div></section>
    <section className="site-container py-20"><div className="mb-10 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><SectionLabel>Architectural provenance</SectionLabel><h2 className="mt-4 font-display text-4xl sm:text-5xl">The details that endure.</h2></div><p className="max-w-sm text-sm leading-relaxed text-muted-foreground">Post-and-beam structure, original proportions, and an unmistakably Californian relationship to the outdoors.</p></div><div className="grid gap-4 md:grid-cols-3"><Photo src={photos.courtyard} alt="Courtyard and original exterior materials" className="aspect-[4/5]" /><Photo src={photos.living} alt="Living room with exposed beams and expansive glass" className="aspect-[4/5]" /><Photo src={photos.night} alt="Illuminated home and roofline at dusk" className="aspect-[4/5]" /></div><div className="mt-8"><TextLink href="/details">View property details</TextLink></div></section>
    <section className="bg-secondary/60 py-20"><div className="site-container grid gap-10 md:grid-cols-2 md:items-center"><Photo src={photos.architects} alt="Dan Palmer and William Krisel in an archival photograph" className="aspect-[4/3]" /><div className="md:pl-10"><SectionLabel>Palmer & Krisel</SectionLabel><h2 className="mt-5 font-display text-4xl">Modernism for everyone.</h2><p className="mt-6 leading-relaxed text-muted-foreground">The architects made good design accessible to ordinary families, drawing thousands of California homes. Their approach brought together glass, beam, landscape, and light — a vocabulary as compelling today as it was in 1958.</p></div></div></section>
    <InquireBand />
  </SiteLayout>;
}

export default Architecture;
